from .repositories import (AcademicEducationRepositoryInterface,
                           AdvisorshipRepositoryInterface,
                           ArticleRepositoryInterface,
                           CampusRepositoryInterface,
                           EducationTypeRepositoryInterface,
                           FellowshipRepositoryInterface,
                           KnowledgeAreaRepositoryInterface,
                           ProfessionalActivityRepositoryInterface,
                           ProductionTypeRepositoryInterface,
                           ResearchProductionRepositoryInterface,
                           ResearcherRepositoryInterface,
                           ResearchGroupRepositoryInterface,
                           RoleRepositoryInterface,
                           UniversityRepositoryInterface)

__all__ = [
    "ResearcherRepositoryInterface",
    "UniversityRepositoryInterface",
    "CampusRepositoryInterface",
    "ResearchGroupRepositoryInterface",
    "KnowledgeAreaRepositoryInterface",
    "RoleRepositoryInterface",
    "AdvisorshipRepositoryInterface",
    "FellowshipRepositoryInterface",
    "AcademicEducationRepositoryInterface",
    "ArticleRepositoryInterface",
    "ProfessionalActivityRepositoryInterface",
    "EducationTypeRepositoryInterface",
    "ProductionTypeRepositoryInterface",
    "ResearchProductionRepositoryInterface",
]
