from .memory_repositories import (InMemoryAdvisorshipRepository,
                                  InMemoryCampusRepository,
                                  InMemoryFellowshipRepository,
                                  InMemoryKnowledgeAreaRepository,
                                  InMemoryResearcherRepository,
                                  InMemoryResearchGroupRepository,
                                  InMemoryRoleRepository,
                                  InMemoryUniversityRepository)
from .sql_repositories import (PostgresAdvisorshipRepository,
                               PostgresCampusRepository,
                               PostgresFellowshipRepository,
                               PostgresKnowledgeAreaRepository,
                               PostgresResearcherRepository,
                               PostgresResearchGroupRepository,
                               PostgresRoleRepository,
                               PostgresUniversityRepository)

__all__ = [
    "PostgresResearcherRepository",
    "PostgresUniversityRepository",
    "PostgresCampusRepository",
    "PostgresResearchGroupRepository",
    "PostgresKnowledgeAreaRepository",
    "PostgresRoleRepository",
    "PostgresAdvisorshipRepository",
    "PostgresFellowshipRepository",
    "InMemoryResearcherRepository",
    "InMemoryUniversityRepository",
    "InMemoryCampusRepository",
    "InMemoryResearchGroupRepository",
    "InMemoryKnowledgeAreaRepository",
    "InMemoryRoleRepository",
    "InMemoryAdvisorshipRepository",
    "InMemoryFellowshipRepository",
]
