from .memory_repositories import (InMemoryAcademicEducationRepository,
                                  InMemoryAdvisorshipRepository,
                                  InMemoryArticleRepository,
                                  InMemoryCampusRepository,
                                  InMemoryEducationTypeRepository,
                                  InMemoryFellowshipRepository,
                                  InMemoryKnowledgeAreaRepository,
                                  InMemoryResearcherRepository,
                                  InMemoryResearchGroupRepository,
                                  InMemoryRoleRepository,
                                  InMemoryUniversityRepository)
from .sql_repositories import (PostgresAcademicEducationRepository,
                               PostgresAdvisorshipRepository,
                               PostgresArticleRepository,
                               PostgresCampusRepository,
                               PostgresEducationTypeRepository,
                               PostgresFellowshipRepository,
                               PostgresKnowledgeAreaRepository,
                               PostgresResearcherRepository,
                               PostgresResearchGroupRepository,
                               PostgresRoleRepository,
                               PostgresUniversityRepository)

__all__ = [
    "PostgresResearcherRepository",
    "PostgresUniversityRepository",
    "PostgresCampusRepository",
    "PostgresResearchGroupRepository",
    "PostgresKnowledgeAreaRepository",
    "PostgresRoleRepository",
    "PostgresAdvisorshipRepository",
    "PostgresFellowshipRepository",
    "InMemoryResearcherRepository",
    "InMemoryUniversityRepository",
    "InMemoryCampusRepository",
    "InMemoryResearchGroupRepository",
    "InMemoryKnowledgeAreaRepository",
    "InMemoryRoleRepository",
    "InMemoryAdvisorshipRepository",
    "InMemoryFellowshipRepository",
    "InMemoryAcademicEducationRepository",
    "InMemoryArticleRepository",
    "InMemoryEducationTypeRepository",
    "PostgresAcademicEducationRepository",
    "PostgresArticleRepository",
    "PostgresEducationTypeRepository",
]
