from .controllers import (AcademicEducationController, ArticleController,
                           ProfessionalActivityController,
                           CampusController, EducationTypeController,
                           FellowshipController, KnowledgeAreaController,
                           ProductionTypeController, ResearchProductionController,
                           ResearcherController, ResearchGroupController,
                           RoleController, UniversityController,
                           AdvisorshipController)

__all__ = [
    "ResearcherController",
    "UniversityController",
    "CampusController",
    "ResearchGroupController",
    "KnowledgeAreaController",
    "RoleController",
    "AdvisorshipController",
    "FellowshipController",
    "AcademicEducationController",
    "ArticleController",
    "ProfessionalActivityController",
    "EducationTypeController",
    "ProductionTypeController",
    "ResearchProductionController",
]
